services:
  - type: web
    name: task-management-api
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    pythonVersion: "3.13.4"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString

databases:
  - name: task-management-db
    plan: free 