services:
  - type: web
    name: task-management-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: docker build -t task-management-api .
    startCommand: docker run -p $PORT:8000 -e DATABASE_URL=$DATABASE_URL task-management-api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString

databases:
  - name: task-management-db
    plan: free 