services:
  - type: web
    name: task-management-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString
      - key: PORT
        value: 8000

databases:
  - name: task-management-db
    plan: free 