services:
  - type: web
    name: task-management-api
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: python3.12 -m pip install -r requirements.txt
    startCommand: python3.12 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString

databases:
  - name: task-management-db
    plan: free 