services:
  - type: web
    name: task-management-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString

databases:
  - name: task-management-db
    plan: free 